version: '2'
# define all services
services:
  suitecrm:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - suite_mysql
    volumes:
      - ./upload:/var/www/html/upload
      - ./public/:/var/www/html/public
      - ./config_si.php/:/var/www/html/config_si.php
      - ./Api/V8/Oauth2/private.key:/var/www/html/Api/V8/Oauth2/private.key
      - ./Api/V8/Oauth2/public.key:/var/www/html/Api/V8/Oauth2/public.key
  suite_mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
