version: '3'
# define all services
services:
  suitecrm:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - suite_mysql
      - suite_elasticsearch
    volumes:
      - .:/var/www/html/
  suite_mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
  suite_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
        restart: unless-stopped
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
